"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../base/app/middleware");
require("../base/connection/middleware");
require("../base/devices/middleware");
require("../base/media/middleware");
require("../dynamic-branding/middleware");
require("../e2ee/middleware");
require("../external-api/middleware");
require("../keyboard-shortcuts/middleware");
require("../no-audio-signal/middleware");
require("../notifications/middleware");
require("../noise-detection/middleware");
require("../old-client-notification/middleware");
require("../power-monitor/middleware");
require("../prejoin/middleware");
require("../remote-control/middleware");
require("../screen-share/middleware");
require("../shared-video/middleware");
require("../web-hid/middleware");
require("../settings/middleware");
require("../talk-while-muted/middleware");
require("../toolbox/middleware");
require("../face-landmarks/middleware");
require("../gifs/middleware");
require("../whiteboard/middleware.web");
require("./middlewares.any");
