"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../dynamic-branding/middleware");
require("../gifs/middleware");
require("../mobile/audio-mode/middleware");
require("../mobile/background/middleware");
require("../mobile/call-integration/middleware");
require("../mobile/external-api/middleware");
require("../mobile/full-screen/middleware");
require("../mobile/navigation/middleware");
require("../mobile/permissions/middleware");
require("../mobile/proximity/middleware");
require("../mobile/wake-lock/middleware");
require("../mobile/react-native-sdk/middleware");
require("../mobile/watchos/middleware");
require("../share-room/middleware");
require("../shared-video/middleware");
require("../whiteboard/middleware.native");
require("./middlewares.any");
