"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../base/devices/reducer");
require("../base/premeeting/reducer");
require("../base/tooltip/reducer");
require("../e2ee/reducer");
require("../face-landmarks/reducer");
require("../feedback/reducer");
require("../keyboard-shortcuts/reducer");
require("../no-audio-signal/reducer");
require("../noise-detection/reducer");
require("../participants-pane/reducer");
require("../power-monitor/reducer");
require("../prejoin/reducer");
require("../remote-control/reducer");
require("../screen-share/reducer");
require("../noise-suppression/reducer");
require("../screenshot-capture/reducer");
require("../talk-while-muted/reducer");
require("../virtual-background/reducer");
require("../web-hid/reducer");
require("./reducers.any");
