import JitsiMeetJS from './_';
export { JitsiMeetJS as default };
export declare const analytics: any;
export declare const browser: any;
export declare const JitsiConferenceErrors: any;
export declare const JitsiConferenceEvents: any;
export declare const JitsiConnectionErrors: any;
export declare const JitsiConnectionEvents: any;
export declare const JitsiConnectionQualityEvents: any;
export declare const JitsiDetectionEvents: any;
export declare const JitsiE2ePingEvents: any;
export declare const JitsiMediaDevicesEvents: any;
export declare const JitsiTrackStreamingStatus: any;
export declare const JitsiRecordingConstants: any;
export declare const JitsiSIPVideoGWStatus: any;
export declare const JitsiTrackErrors: any;
export declare const JitsiTrackEvents: any;
export declare const RTCStatsEvents: any;
