"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MuteRemoteParticipantsVideoDialog = exports.MuteEveryonesVideoDialog = exports.MuteEveryoneDialog = exports.KickRemoteParticipantDialog = exports.GrantModeratorDialog = exports.DemoteToVisitorDialog = void 0;
var DemoteToVisitorDialog_1 = require("./web/DemoteToVisitorDialog");
Object.defineProperty(exports, "DemoteToVisitorDialog", { enumerable: true, get: function () { return DemoteToVisitorDialog_1.default; } });
var GrantModeratorDialog_1 = require("./web/GrantModeratorDialog");
Object.defineProperty(exports, "GrantModeratorDialog", { enumerable: true, get: function () { return GrantModeratorDialog_1.default; } });
var KickRemoteParticipantDialog_1 = require("./web/KickRemoteParticipantDialog");
Object.defineProperty(exports, "KickRemoteParticipantDialog", { enumerable: true, get: function () { return KickRemoteParticipantDialog_1.default; } });
var MuteEveryoneDialog_1 = require("./web/MuteEveryoneDialog");
Object.defineProperty(exports, "MuteEveryoneDialog", { enumerable: true, get: function () { return MuteEveryoneDialog_1.default; } });
var MuteEveryonesVideoDialog_1 = require("./web/MuteEveryonesVideoDialog");
Object.defineProperty(exports, "MuteEveryonesVideoDialog", { enumerable: true, get: function () { return MuteEveryonesVideoDialog_1.default; } });
var MuteRemoteParticipantsVideoDialog_1 = require("./web/MuteRemoteParticipantsVideoDialog");
Object.defineProperty(exports, "MuteRemoteParticipantsVideoDialog", { enumerable: true, get: function () { return MuteRemoteParticipantsVideoDialog_1.default; } });
